### ISSUE TITLE
Doplnit spoluautory do readme GitHub + MyBB extend site

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_CZE-translation-1.8.x#25]
@uzbugg @BKPepe

**Comment by Cu8eeeR** [comment]
Readme na GitHub upraveno; popis na MyBB extend site bude upraven po nahrání nejnovější verze

**Comment by Eldenroot** [comment]
Hotovo - https://community.mybb.com/mods.php?action=view&pid=280
