### ISSUE TITLE
Přidat nebo upravit v anglickém překladu

### ISSUE THREAD

**Issue by BKPepe** [Eldenroot/MyBB_CZE-translation-1.8.x#27]
Přidat do časových pásem:
Prahu, Bratislavu

Upravit: (pokud není již upraveno)
Dhakra na Dhaka

**Comment by BKPepe** [comment]
Vytvořil jsem [pull request](https://github.com/mybb/mybb/pull/3226) do repozitáře MyBB.

**Comment by Eldenroot** [comment]
Díky! Zrovna jsem se na to chystal v průběhu týdne ať se to stihne do vydání MyBB 1.8.16
