### ISSUE TITLE
Čeština pro administraci nelze vybrat v nastavení.

### ISSUE THREAD

**Issue by ghost** [Eldenroot/MyBB_CZE-translation-1.8.x#31]
Dobrý den, děkuji moc za překlad, ovšem potýkám se s menším problémem.

Přidal jsem příspěvek do oficiálního tématu k češtině na fóru mybb.
https://community.mybb.com/thread-161793.html?highlight=czech

Jde o to, že jak chci nastavit češtinu pro administrac v

Admin Control Panel Language
Please select a language to use in the Admin Control Panel.

mám tam pouze English (American), čeština zde není.

Děkuji za pomoc

**Comment by Eldenroot** [comment]
Zdravím, je nutné změnit volbu na řádku 21 v souboru czech.php

https://github.com/BKPepe/MyBB_CZE-translation-1.8.x/blob/master/czech.php

**Comment by Eldenroot** [comment]
Opraveno v ACP větvi
