### ISSUE TITLE
Čas a datum - překlad

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_CZE-translation-1.8.x#32]
Jak psal @chodik tak zde nejsou přeloženy některé časy... vím, že zde byla změna ve verzi MyBB 1.8.13, pokud se nepletu a pokud zde nejsou nové lang stringy vloženy, tak se používají anglické defaultní. Každopádně na mém fóru to funguje bez problému (MyBB 1.8.15).

Tady je ještě nastavení času a data (aby se nezobrazovalo AM/PM)
![image](https://user-images.githubusercontent.com/778890/40380863-801ded14-5dfa-11e8-9328-f7073db13969.png)

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/40381076-0ea708a4-5dfb-11e8-888e-9bef052bcc46.png)

překlad zde určitě je

**Comment by chodik** [comment]
Kde se nastavuje - today, yesterday ? Nemůžu to nějak najít. Dík

**Comment by Eldenroot** [comment]
ACP -> Languages -> Edit variables
