### ISSUE TITLE
Chybějící pole pro e-mail

### ISSUE THREAD

**Issue by ghost** [Eldenroot/MyBB_CZE-translation-1.8.x#38]
Ahoj, všiml jsem si že mi na fóru při registraci chybí u prvního pole, kde se má zadávat emailová adresa text e-mail. Je zde pouze potvrdit e-mailovou adresu.

Je možné že je tato chyba nějak ve spojitosti s překladem ?
Protože jak jsem si přepnul na anglický jazyk tak tam ta fráze je.

Zde je obrázek:
vše na totožném fóru

CZ verze:

![](https://i.imgur.com/wNUFGjp.jpg)

EN verze:
![](https://i.imgur.com/tpbzUCC.jpg)
Tipuju, že bude problém ve vynechané frázi v CZ překladu, co myslíte ?

Díky

**Comment by BKPepe** [comment]
Ahoj,
o téhle chybě vím a bude opravena pro překlad MyBB 1.8.16.

**Comment by NefCZ** [comment]
Díky, když už jsme u těch chyb. Tak jsem objevil ještě jednu.

![](https://i.imgur.com/Hv3sTtB.jpg)

* Toto pole je vyžadávno.

**Comment by BKPepe** [comment]
Obávám se, že tohle asi nepůjde přeložit. Otevřel jsem si anglický překlad a nenašel jsem, že by to bylo možné přeložit, ale podívám se, co se s tím dá dělat. Pokud by to šlo nějak snadno opravit, tak bych to poslal do upstreamu.

**Comment by Eldenroot** [comment]
Mozna ze je to hardcoded v js pro captcha

**Comment by NefCZ** [comment]
Jasně, jen ještě mimo téma, rád bych se zeptal, je možné nějak editovat datum, které se zobrazuje při přidání miniatury do příspěvku ? Nejlépe kdyby to šlo uplně vypnout apod. Nemohu to dohledat.

![](https://i.imgur.com/3uoA1SS.jpg)

**Comment by Eldenroot** [comment]
toto by melo byt mozne pres editaci teplate - skupina attachment, minimalne to zkus ;)

**Comment by NefCZ** [comment]
Jo takhle, tak jsem zjistil že to není součástí fóra ale je to asi překlep. Protože v EN verzi toto vůbec není u miniatury. Zkusím to dohledat a napsat zde kde se to nachází, mělo by s to taky zahrnout do oprav. Navíc čas a všechny detaily při nahrání miniatury jdou zobrazit po najetí na miniaturu.

**Comment by Eldenroot** [comment]
Mrknu na to dnes/zitra. Podle mne to ale u nas na foru funguje spravne (miniatury)

**Comment by NefCZ** [comment]
Taky se to snažím najít, aha no já mám češtinu z extendu tu poslední zveřejněnou. A pamatuju už při instalaci mybb cca tak před 3 měsíci to tam u těch miniatur bylo taky.

**Comment by Eldenroot** [comment]
Mas posledni verzi? Kdyztak vydrz a jakmile @bkpepe dokonci jeho pr a mergneme ho do masteru tak zkusit

**Comment by NefCZ** [comment]
Ano poslední verzi mybb i cz, u ciste instalace u té to delalo taky. A momentálně jen 3 pluginy.
Jo v pohodě.

**Comment by BKPepe** [comment]
Opraveno. https://github.com/BKPepe/MyBB_CZE-translation-1.8.x/commit/d3406921cfbd9dd4f5a42f16c567a9ed240856ff

**Comment by Eldenroot** [comment]
Perfektni, diky

**Comment by BKPepe** [comment]
Je to možné stáhnout z [mého repozitáře (branch 1816)](https://github.com/BKPepe/MyBB_CZE-translation-1.8.x/tree/1816). S tím, že na starších verzích MyBB na hlavní stránce fóra ve spodní části, kde jsou ikonky, tak u uzamčeného vlákna se nezobrazí text a to samé když si otevřeš kategorii, protože zde došlo k úpravám. 

S tím, že překlad je zkontrolovaný, díky @Eldenroot tak s vydáním 1.8.16 se ten překlad mergne (sloučí) do tohoto repozitáře a vydá se to.

**Comment by Eldenroot** [comment]
Jinak mergednuto, muzes stahnout primo odsud na download vpravo nahore.

**Comment by NefCZ** [comment]
Díky, mělo by to být funkční.

**Comment by NefCZ** [comment]
Prosím ještě o edit, je tam malé e.
![](https://i.imgur.com/EV7OFkc.jpg)
Snad budu moct do budoucna více pomoct a přidávat změny již do překladu ať jen nepíšu instrukce :-)

**Comment by BKPepe** [comment]
Ale tohle je opravené.

 https://github.com/BKPepe/MyBB_CZE-translation-1.8.x/blob/1816/czech/member.lang.php#L80

https://github.com/Eldenroot/MyBB_CZE-translation-1.8.x/blob/master/czech/member.lang.php#L80

**Comment by NefCZ** [comment]
Díky za opravu, vše super.
