### ISSUE TITLE
Posunuté tlačítko pro odeslání emailu - způsobeno překladem.

### ISSUE THREAD

**Issue by ghost** [Eldenroot/MyBB_CZE-translation-1.8.x#39]
Všiml jsem si další věci, posunutého tlačítka pro odeslání emailu.
Tipuju, že to je způsobeno tím, že není přidán text E-mail v CZ překladu, po přidání by se to mělo srovnat. Nebo to není přidáno s nějakého jiného důvodu ?

**EN verze**
![](https://i.imgur.com/6WN0dyt.jpg)

**CZ verze**
![](https://i.imgur.com/3s5hhC0.jpg)

**Comment by Eldenroot** [comment]
Ano, máš pravdu, chybí překlad pro "email" @BKPepe

**Comment by BKPepe** [comment]
Ahoj,
podívám se na to až zitra. Dříve se k počítači nedostanu.

**Comment by BKPepe** [comment]
Oprava:
https://github.com/BKPepe/MyBB_CZE-translation-1.8.x/commit/73904434a0f06ccc307547b98d9609b6cf3845ee

Cherry picknu to během večera.

**Comment by NefCZ** [comment]
Skvělé ! hned to vypadá lépe. Díky za opravu.

**Comment by BKPepe** [comment]
https://github.com/Eldenroot/MyBB_CZE-translation-1.8.x/commit/43b6c3cb6975d641fa8b5b2ce2a798d927542635
