### ISSUE TITLE
Chybí překlad pro zavřené téma

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_CZE-translation-1.8.x#40]
![image](https://user-images.githubusercontent.com/778890/42333760-e046e850-807b-11e8-8e16-4b9e601bfd3a.png)

**Comment by BKPepe** [comment]
Tohle jsem si ověřoval, že to nefunguje na MyBB 1.8.15, ale na MyBB 1.8.16 by to mělo fungovat.

**Comment by Eldenroot** [comment]
Od včerejška jedu na MyBB 1.8.16 a bohužel není, chyba lang stringu? V eng funguje
https://github.com/mybb/mybb/commit/5f6944a0fdbc52447bc77dba7a8e40bd75790420
