### ISSUE TITLE
Chyba verze

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_CZE-translation-1.8.x#41]
Chybí změna číselného označení verze  1813 na 1816, opravil bych to až bude vydána nová čeština s administrací... jen kosmetická vada

**Comment by BKPepe** [comment]
To by mělo být. Viz commit https://github.com/Eldenroot/MyBB_CZE-translation-1.8.x/blob/master/czech.php

**Comment by Eldenroot** [comment]
Tak potom jsi na MyBB nahrál starou verzi... zkontroluji to

**Comment by BKPepe** [comment]
Máš pravdu. Teď na to koukám. :(

**Comment by Eldenroot** [comment]
Opravil jsem to
