### ISSUE TITLE
Chyba v překladu u přihlašování

### ISSUE THREAD

**Issue by note85** [Eldenroot/MyBB_CZE-translation-1.8.x#44]
Ahoj, všiml jsem si menší chyby v překladu.
Když se chci na fórum přihlásit, požaduje to po mě -  e-mail.
Požaduje to přesto i když mám v administraci nastaveno že chci aby se lidé přihlašovali pomocí přezdívky.

Přepnul jsem fórum do angličtiny a najednou tam bylo username.

Co je třeba udělat: přejmenovat u části v překladu místo e-mail na přezdívka nebo vaše přezdívka.

Chápu že než to bude vydáno v ostré verzi tak to potrvá, je proto možné mě trochu nasměrovat kde toto najdu abych si to mohl sám opravit ? Díky moc.

**Comment by note85** [comment]
Tak nejspíš jsem to našel.
Nachází se to v souboru inc/languages/czech/global.lang.php

**Český překlad**

$l['login_username'] = "Uživatelské jméno:";
$l['login_username'] = "E-mail";
$l['login_username2'] = "Uživatelské jméno/E-mail:";


**Orignál EN překlad**

$l['reset_button'] = "Reset";
$l['username'] = "Username:";
$l['username1'] = "Email:";
$l['username2'] = "Username/Email:";
$l['password'] = "Password:";
$l['login_username'] = "Username:";
$l['login_username1'] = "Email:";
$l['login_username2'] = "Username/Email:";


Dle překladu to vypadá, že je to vyplněno správně tak potom nerozumím kde může být chyba.

**Comment by Eldenroot** [comment]
Hmm, toto je zajímavé - @BKPepe - používáme správně lang var v cz balíčku? Kdyby to byla chyba MyBB jádra, tak to nebude fungovat ani v anglickém překladu. Zkusím se na to podívat.

@note85 - vydání češtiny je nezávislé na vydání nové verze MyBB, opravu mlžeme vydat kdykoliv případně si ji můžeš stáhnout přímo z GitHubu a přepsat soubor.

**Comment by BKPepe** [comment]
Zdravím,

tak jsem našel, kde se nachází tato chyba a je zřejmé i z toho kódu, co @note85 sem zkopíroval.

Stačí, když si porovnáte tuhle část kódu, co je v CZ překladu:
```
$l['login_username'] = "Uživatelské jméno:";
$l['login_username'] = "E-mail";
$l['login_username2'] = "Uživatelské jméno/E-mail:";
```
Pak se podíváte na část kódu, co je v AJ:
```
$l['login_username'] = "Username:";
$l['login_username1'] = "Email:";
$l['login_username2'] = "Username/Email:";
```

Zjistíte, že nějakým zvláštním způsobem se mi nedopatřením ztratila 1, takže to funguje tak, že se prvně načte první hodnota, ale následně se přepíše následující hodnotou, protože se jedná o stejný jazykový string.

Této chyby jsem se dopustil v následujícím commitu: https://github.com/Eldenroot/MyBB_CZE-translation-1.8.x/commit/ad585983453a33350461718a739e08bb0aad6e04, kdy došlo ke sjednocení překladu souboru global.lang.php jak v UCP, tak v ACP.

Stačí si ztracenou 1 připsat a bude to fungovat, tak jak má.

**Comment by Eldenroot** [comment]
@BKPepe - díky za debug!
