### ISSUE TITLE
Doplnění pár drobných oprav

### ISSUE THREAD

**Issue by Ashus** [Eldenroot/MyBB_CZE-translation-1.8.x#47]
Jsou to jen drobnosti, ale např. chybějící mezera vypadá po odeslání příspěvku na frontendu nehezky:

_admin\global.lang.php_
```
$l['today_rel'] = "<span title=\"{1}\">Dnes</span>";
$l['yesterday_rel'] = "<span title=\"{1}\">Včera</span>";
...
$l['generated_in'] = "Vygenerováno za {1} pomocí <a href=\"{2}\" target=\"_blank\">{3} dotazů</a>. Využití paměti: {4}";
```

_global.lang.php_
`$l['rel_less_than'] = "méně než ";`

**Comment by BKPepe** [comment]
Ahoj,

díky za nahlášení. Podívám se na to, když bych potřeboval vědět více informací, tak dám vědět.

Nevím, zda se na to ještě dnes podívám, ale během víkendu se na to určitě podívám.

**Comment by Ashus** [comment]
Prosím pěkně ještě o kontrolu klíčů na začátku soboru: czech/admin/global.lang.php
today_rel
yesterday_rel
