### ISSUE TITLE
UCP -> Změnit avatar

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_CZE-translation-1.8.x#51]
Myslím si, že je zde chybějící překlad + jedna chybička.

1) chybějící překlad pod URL avataru
2) u odkazu na Gravatar je navíc >

![image](https://user-images.githubusercontent.com/778890/50599332-0e635500-0eae-11e9-9094-105d2b480dcf.png)

**Comment by BKPepe** [comment]
1. invalid.
Nejspíše způsobené pluginem, protože na mém [testovacím fóru](https://ctrlv.cz/9KHP) se to nenachází a dokonce se to nenachází ani v angličtině.

2. will be fixed soon.
