### ISSUE TITLE
MODCP

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_CZE-translation-1.8.x#58]
![image](https://user-images.githubusercontent.com/778890/53659111-fbc18e00-3c5a-11e9-9e42-973f2e815090.png)

- pár věcí - nevím zdali nepoužít malé písmenko "v" u zobrazení fóra
- hlášení č. - není to spíše kolikrát bylo již nahlášeno?
- nejnověji nahlášené - možná lépe nejnověji nahlásil, nahlášeno

**Comment by BKPepe** [comment]
Nejnověji nahlášeno zní líp. S malým "v" u zobrazení fóra nemám problém. Hlášení č. vypadá blbě. Souhlasím.

**Comment by Eldenroot** [comment]
Můžu poprosit o PR? Díky

**Comment by BKPepe** [comment]
V pruběhu týdne se snad k tomu dostanu. Doufám, že i dříve.
