### ISSUE TITLE
Odkaz v messages.lang.php pm_subscription

### ISSUE THREAD

**Issue by McLaynV** [Eldenroot/MyBB_CZE-translation-1.8.x#60]
https://github.com/Eldenroot/MyBB_CZE-translation-1.8.x/blob/3be658a2965ab0f9339ab1aad3867223161d97ce/czech/messages.lang.php#L487

Aktuální:
`[url]{5}/usercp.php?action=removesubscription&tid={7}&key={8}&my_post_key={9}[/url]`
https://example.com/usercp.php?action=removesubscription&tid=362&key=56f813f3ee8ee2ff616d5cff7caaa31c&my_post_key={9}

Správně (podle anglické verze a taky jsem to otestoval):
`[url]{5}/usercp.php?action=removesubscription&tid={7}&my_post_key={8}[/url]`
https://example.com/usercp.php?action=removesubscription&tid=362&my_post_key=56f813f3ee8ee2ff616d5cff7caaa31c

Anglická:
https://github.com/mybb/mybb/blob/e5695359da73d0c79f42272d4f1eaa35f6dc5155/inc/languages/english/messages.lang.php#L496

**Comment by BKPepe** [comment]
Díky za nahlášení. Podívám se na to.

**Comment by McLaynV** [comment]
Je to soukromá zpráva, kterou uživatel dostane, když má zapnuté subscribe na vlákno do soukromých zpráv.

**Comment by BKPepe** [comment]
Dostal jsem se k tomu až teď. Chybu se mi podařilo zreprodukovat. Ještě dnes připravím pull request, kde to bude opravené.
