### ISSUE TITLE
MyBB 1.8.25 - změny

### ISSUE THREAD

**Issue by Eldenroot** [Eldenroot/MyBB_CZE-translation-1.8.x#84]
Changes related to the new upcoming release of MyBB.

**Comment by Eldenroot** [comment]
Pouze security release - @BKPepe - plánujeme něco přidat, nebo můžeme bumpnout rovnou na 1.8.26

**Comment by BKPepe** [comment]
Verze 1.8.25 také řešení bezpečnostní zranitelnosti a nedošlo zde k úpravám jazyků.
Viz https://mybb.com/versions/1.8.25/
