### ISSUE TITLE
Oznámení chyb od ZS

### ISSUE THREAD

**Issue by zdenekstanek** [Eldenroot/MyBB_CZE-translation-1.8.x#85]
Soubor: messages.lang.php
Proměnná: $l['email_reportpost']
Chyba: {7} **má být** {6}

Soubor: messages.lang.php
Proměnná: $l['email_reportprofile']
Chyba: uživateel **má být** uživatele

**Comment by BKPepe** [comment]
Dobrý den, @zdenekstanek,

mohu potvrdit, že obě chyby se nacházely v překladu a děkujeme za nahlášení. Vydávat prozatím novou verzi překladu nebudeme a opravíme to jakmile vyvojáři MyBB vydají novou verzi.  V tuto chvíli pokud jste již neučinil, tak je možné chyby opravit ručně v daném souboru, případně je možné převzít změny z pull requestu.

Přidám jen menší zajímavost a to je, že na chybu kterou jste narazil v proměnné `$l['email_reportpost']` se v překladu nacházela více než 5 let. 

Ještě jednou děkujeme za zlepšování českého překladu MyBB.

S pozdravem
JS
